// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

export {default as SForm} from './SForm.vue'
export {default as SInput} from './SInput.vue'
